print('======= Data Diri Mahasiswa =======')
nim = str(input('NIM : '))
nama = str(input('Nama Lengkap : '))
jurusan = str(input('Jurusan : '))
alamat = str(input('Alamat : '))

print('Hasil Cetak Data')
print('NIM : ' + nim)
print('Nama : ' + nama)
print('Jurusan : ' + jurusan)
print('Alamat : ' + alamat)
